#$ -cwd
#$ -o output/
#$ -e output/
module load mpi/openmpi41-x86_64
export OMPI_MCA_btl_openib_allow_ib=1

# aktivirati virtualno okruženje
# assuming venv is created and pip mpi4py installed
source venv-mpi4py/bin/activate

# podignuti MPI knjižnicu
# pip install --upgrade pip
# pip install mpi4py

# potjerati python program
time mpirun -np ${NSLOTS:-1} python3 double-mpi4py.py

# deaktivirati virtualno okruženje
deactivate